#pragma once

#include <stdint.h>

#define MSP_ELRS_FUNC 0x4578

#define MSP_VTX_CONFIG 88
#define MSP_SET_VTX_CONFIG 89
#define MSP_VTXTABLE_BAND 137
#define MSP_SET_VTXTABLE_BAND 227
#define MSP_VTXTABLE_POWERLEVEL 138
#define MSP_SET_VTXTABLE_POWERLEVEL 228
#define MSP_EEPROM_WRITE 250

// ELRS-specific opcodes shared by TX and RX.
#define MSP_ELRS_RF_MODE 0x06
#define MSP_ELRS_TX_PWR 0x07
#define MSP_ELRS_TLM_RATE 0x08
#define MSP_ELRS_BIND 0x09
#define MSP_ELRS_REQU_VTX_PKT 0x0B
#define MSP_ELRS_SET_TX_BACKPACK_WIFI_MODE 0x0C
#define MSP_ELRS_SET_VRX_BACKPACK_WIFI_MODE 0x0D
#define MSP_ELRS_SET_RX_WIFI_MODE 0x0E
#define MSP_ELRS_GET_BACKPACK_VERSION 0x10
#define MSP_ELRS_BACKPACK_CRSF_TLM 0x11
#define MSP_ELRS_POWER_CALI_GET 0x20
#define MSP_ELRS_POWER_CALI_SET 0x21
#define MSP_ELRS_RXTX_CONFIG 0x2D
#define MSP_ELRS_BACKPACK_CONFIG 0x30
#define MSP_ELRS_BACKPACK_CONFIG_TLM_MODE 0x31
#define MSP_ELRS_MAVLINK_TLM 0xFD

#define ENCAPSULATED_MSP_HEADER_CRC_LEN 4
#define ENCAPSULATED_MSP_MAX_PAYLOAD_SIZE 4
#define ENCAPSULATED_MSP_MAX_FRAME_LEN \
  (ENCAPSULATED_MSP_HEADER_CRC_LEN + ENCAPSULATED_MSP_MAX_PAYLOAD_SIZE)

enum class MSP_ELRS_RXTX_CONFIG_SUBCMD : uint8_t {
  UID = 0x00,
  BIND_PHRASE = 0x01,
  MODEL_ID = 0x0A,
};
