/*******************************************************************************
 * Minimal BLE stack sizing for the standalone ELRS BLE GATT probe.
 *
 * The WiseConnect BLE component sources include this file directly. Keep these
 * values small until the standalone BLE path is proven on hardware.
 ******************************************************************************/

#ifndef BLE_CONFIG_H
#define BLE_CONFIG_H

#define RSI_BLE_SET_RAND_ADDR "00:23:A7:12:34:56"

#define CLEAR_ACCEPTLIST 0x00
#define ADD_DEVICE_TO_ACCEPTLIST 0x01
#define DELETE_DEVICE_FROM_ACCEPTLIST 0x02

#define RSI_BLE_DEV_ADDR_RESOLUTION_ENABLE 0

#ifdef SLI_SI91X_MCU_INTERFACE
#define RSI_BLE_MAX_NBR_ATT_REC 20
/* Match the Silicon Labs ble_per SOC example for first-boot NWP sizing. */
#define RSI_BLE_NUM_CONN_EVENTS 4
#else
#define RSI_BLE_MAX_NBR_ATT_REC 80
#define RSI_BLE_NUM_CONN_EVENTS 20
#endif

#define RSI_BLE_MAX_NBR_PERIPHERALS 3
#define RSI_BLE_MAX_NBR_CENTRALS 1
#define RSI_BLE_MAX_NBR_ATT_SERV 10
#define RSI_BLE_NUM_REC_BYTES 0x40

#define RSI_BLE_GATT_ASYNC_ENABLE 0
#define RSI_BLE_GATT_INIT 0
#define BLE_SIMPLE_GATT 0
#define RSI_BLE_INDICATE_CONFIRMATION_FROM_HOST 0
#define RSI_BLE_MTU_EXCHANGE_FROM_HOST 0
#define RSI_BLE_SET_SCAN_RESP_DATA_FROM_HOST 0
#define RSI_BLE_DISABLE_CODED_PHY_FROM_HOST 0
#define RSI_BLE_ENABLE_ADV_EXTN 1
#define RSI_BLE_AE_MAX_ADV_SETS 1

#define RSI_BLE_ADV_TYPE UNDIR_CONN
#define RSI_BLE_ADV_FILTER_TYPE ALLOW_SCAN_REQ_ANY_CONN_REQ_ANY
#define RSI_BLE_ADV_DIR_ADDR_TYPE LE_PUBLIC_ADDRESS
#define RSI_BLE_ADV_DIR_ADDR "00:15:83:6A:64:17"
#define RSI_BLE_ADV_INT_MIN 0x100
#define RSI_BLE_ADV_INT_MAX 0x200
#define RSI_BLE_ADV_CHANNEL_MAP 0x07
#define RSI_BLE_START_ADV 0x01
#define RSI_BLE_STOP_ADV 0x00

#ifdef SLI_SI915
#define RSI_BLE_PWR_INX 75
#else
#define RSI_BLE_PWR_INX 30
#endif
#define RSI_BLE_PWR_INX_DBM 0

#define BLE_DISABLE_DUTY_CYCLING 0
#define BLE_DUTY_CYCLING 1
#define BLR_DUTY_CYCLING 2
#define BLE_4X_PWR_SAVE_MODE 4
#define RSI_BLE_PWR_SAVE_OPTIONS BLE_DISABLE_DUTY_CYCLING

#define UNDIR_CONN 0x80
#define DIR_CONN 0x81
#define UNDIR_SCAN 0x82
#define UNDIR_NON_CONN 0x83
#define DIR_CONN_LOW_DUTY_CYCLE 0x84

#define LE_LIMITED_DISCOVERABLE 0x01
#define LE_GENERAL_DISCOVERABLE 0x02
#define LE_BR_EDR_NOT_SUPPORTED 0x04

#define ALLOW_SCAN_REQ_ANY_CONN_REQ_ANY 0x00
#define ALLOW_SCAN_REQ_ACCEPT_LIST_CONN_REQ_ANY 0x01
#define ALLOW_SCAN_REQ_ANY_CONN_REQ_ACCEPT_LIST 0x02
#define ALLOW_SCAN_REQ_ACCEPT_LIST_CONN_REQ_ACCEPT_LIST 0x03

#define LE_PUBLIC_ADDRESS 0x00
#define LE_RANDOM_ADDRESS 0x01
#define LE_RESOLVABLE_PUBLIC_ADDRESS 0x02
#define LE_RESOLVABLE_RANDOM_ADDRESS 0x03
#define ALL_PHYS 0x00

#define RSI_BLE_SCAN_TYPE SCAN_TYPE_ACTIVE
#define RSI_BLE_SCAN_FILTER_TYPE SCAN_FILTER_TYPE_ALL
#define RSI_BLE_START_SCAN 0x01
#define RSI_BLE_STOP_SCAN 0x00

#define SCAN_TYPE_ACTIVE 0x01
#define SCAN_TYPE_PASSIVE 0x00
#define SCAN_FILTER_TYPE_ALL 0x00
#define SCAN_FILTER_TYPE_ONLY_ACCEPT_LIST 0x01

#define LE_SCAN_INTERVAL 0x0100
#define LE_SCAN_WINDOW 0x0050
#define CONNECTION_INTERVAL_MIN 0x00A0
#define CONNECTION_INTERVAL_MAX 0x00A0
#define CONNECTION_LATENCY 0x0000
#define SUPERVISION_TIMEOUT 0x07D0

#define RSI_SEL_INTERNAL_ANTENNA 0x00
#define RSI_SEL_EXTERNAL_ANTENNA 0x01

#endif /* BLE_CONFIG_H */
